// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/Garhlz",
        "contact": {
            "name": "Elaine",
            "url": "https://github.com/Garhlz",
            "email": "your.email@example.com"
        },
        "license": {
            "name": "MIT License",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/albums": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取专辑的分页列表，支持按专辑名或艺术家名进行搜索，并可按指定字段排序。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "专辑 (Album)"
                ],
                "summary": "获取专辑列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "搜索关键词 (匹配专辑名或艺术家名)",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "latest",
                            "release_date"
                        ],
                        "type": "string",
                        "description": "排序字段 (latest, release_date)",
                        "name": "sortBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.PaginatedResponseDTO"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "List": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.AlbumListDTO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"无效的查询参数\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "{\"error\": \"需要认证\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "{\"error\": \"获取专辑列表失败\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/albums/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据专辑ID获取其详细信息。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "专辑 (Album)"
                ],
                "summary": "获取专辑详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "专辑 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Album"
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"无效的专辑ID\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "{\"error\": \"需要认证\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "{\"error\": \"专辑未找到\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "{\"error\": \"获取专辑失败\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/albums/{id}/songs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据专辑ID获取其歌曲的分页列表，支持搜索和排序。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "专辑 (Album)"
                ],
                "summary": "获取专辑的歌曲列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "专辑 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "歌曲列表的页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页的歌曲数量",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "在歌曲中搜索的关键词 (匹配歌曲名或专辑名)",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "oldest",
                            "latest",
                            "play_count",
                            "like_count"
                        ],
                        "type": "string",
                        "description": "歌曲列表的排序字段",
                        "name": "sortBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.PaginatedResponseDTO"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "List": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.SongDetailDTO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"无效的ID或查询参数\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "{\"error\": \"需要认证\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "{\"error\": \"获取歌曲列表失败\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/artists/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据艺术家ID获取其详细信息。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "艺术家 (Artist)"
                ],
                "summary": "获取艺术家详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "艺术家 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Artist"
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"无效的艺术家ID\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "{\"error\": \"需要认证\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "{\"error\": \"艺术家未找到\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "{\"error\": \"获取艺术家失败\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/artists/{id}/songs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据艺术家ID获取其歌曲的分页列表，支持搜索和排序。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "艺术家 (Artist)"
                ],
                "summary": "获取艺术家的歌曲列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "艺术家 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "歌曲列表的页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页的歌曲数量",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "在歌曲中搜索的关键词 (匹配歌曲名或专辑名)",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "oldest",
                            "latest",
                            "play_count",
                            "like_count"
                        ],
                        "type": "string",
                        "description": "歌曲列表的排序字段",
                        "name": "sortBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.PaginatedResponseDTO"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "List": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.SongDetailDTO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"无效的ID或查询参数\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "{\"error\": \"需要认证\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "{\"error\": \"获取歌曲列表失败\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "用户使用用户名和密码登录，成功后返回 JWT Token 和用户信息。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证 (Auth)"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "用户登录凭证",
                        "name": "loginRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\": \"登录成功\", \"token\": \"...\", \"user_id\": 1}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"用户名和密码不能为空\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "{\"error\": \"密码不正确\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "{\"error\": \"用户不存在\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "{\"error\": \"登录时发生未知错误\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "根据提供的用户名和密码等信息，创建一个新的用户账户。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证 (Auth)"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "用户注册信息",
                        "name": "registerRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "{\"message\": \"注册成功\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"无效的请求参数\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "{\"error\": \"该用户名已被注册\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "{\"error\": \"注册失败，请稍后重试\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/comments/{commentId}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新当前认证用户发表的一条评论。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论 (Comment)"
                ],
                "summary": "更新我的评论",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "评论 ID",
                        "name": "commentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新的评论内容",
                        "name": "updateRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateCommentRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\": \"更新成功\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除当前认证用户发表的一条评论（及其所有回复）。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论 (Comment)"
                ],
                "summary": "删除我的评论",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "评论 ID",
                        "name": "commentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\": \"删除成功\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/comments/{commentId}/like": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "对一条评论进行点赞。如果已经点赞，则取消点赞。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论 (Comment)"
                ],
                "summary": "点赞或取消点赞评论",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "评论 ID",
                        "name": "commentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.LikeCommentResponseDTO"
                        }
                    }
                }
            }
        },
        "/comments/{commentId}/replies": {
            "get": {
                "description": "根据一条父评论的ID，获取它的所有回复列表（不分页）。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论 (Comment)"
                ],
                "summary": "获取评论回复",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "父评论 ID",
                        "name": "commentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.CommentDTO"
                            }
                        }
                    }
                }
            }
        },
        "/me/liked-songs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前认证用户（通过JWT Token识别）的喜欢歌曲分页列表，支持搜索和排序。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "喜欢 (Like)"
                ],
                "summary": "获取我喜欢的歌曲列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "搜索关键词 (匹配歌曲名或艺术家名)",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "latest",
                            "oldest",
                            "name",
                            "duration"
                        ],
                        "type": "string",
                        "description": "排序字段 (latest, oldest, name, duration)",
                        "name": "sortBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.PaginatedResponseDTO"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "List": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.SongDetailDTO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"无效的查询参数\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "{\"error\": \"需要认证\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "{\"error\": \"获取列表失败\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/me/liked-songs/{songId}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "将一首指定的歌曲添加到当前认证用户的“我喜欢”列表中。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "喜欢 (Like)"
                ],
                "summary": "添加歌曲到我喜欢列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "歌曲 ID",
                        "name": "songId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "{\"message\": \"添加成功\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"无效的歌曲ID格式\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "{\"error\": \"需要认证\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "{\"error\": \"歌曲不存在\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "{\"error\": \"已经喜欢过这首歌了\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "{\"error\": \"操作失败，请稍后重试\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "将一首指定的歌曲从当前认证用户的“我喜欢”列表中移除。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "喜欢 (Like)"
                ],
                "summary": "从我喜欢列表移除歌曲",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "歌曲 ID",
                        "name": "songId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\": \"取消成功\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"无效的歌曲ID格式\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "{\"error\": \"需要认证\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "{\"error\": \"您尚未喜欢这首歌\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "{\"error\": \"操作失败，请稍后重试\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/me/playlists": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "歌单 (Playlist)"
                ],
                "summary": "获取我的歌单列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.PaginatedResponseDTO"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "List": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.PlaylistInfoDTO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "歌单 (Playlist)"
                ],
                "summary": "创建我的新歌单",
                "parameters": [
                    {
                        "description": "创建歌单请求",
                        "name": "createRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreatePlaylistRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "{\"id\": 1, \"message\": \"创建成功\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/me/playlists/{playlistId}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "歌单 (Playlist)"
                ],
                "summary": "更新我的歌单信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "歌单 ID",
                        "name": "playlistId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新歌单请求",
                        "name": "updateRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdatePlaylistRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\": \"更新成功\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "歌单 (Playlist)"
                ],
                "summary": "删除我的歌单",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "歌单 ID",
                        "name": "playlistId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\": \"删除成功\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/me/playlists/{playlistId}/songs": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "歌单 (Playlist)"
                ],
                "summary": "向我的歌单添加歌曲",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "歌单 ID",
                        "name": "playlistId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "添加歌曲请求",
                        "name": "addSongRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddSongToPlaylistRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "{\"message\": \"添加成功\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/me/playlists/{playlistId}/songs/{songId}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "歌单 (Playlist)"
                ],
                "summary": "从我的歌单移除歌曲",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "歌单 ID",
                        "name": "playlistId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "歌曲 ID",
                        "name": "songId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\": \"移除成功\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/me/profile": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新当前认证用户（通过JWT Token识别）的个人资料。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户信息 (User)"
                ],
                "summary": "更新当前登录用户信息",
                "parameters": [
                    {
                        "description": "要更新的用户信息",
                        "name": "updateRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\": \"用户信息更新成功\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"请求参数格式错误\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "{\"error\": \"需要认证\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "{\"error\": \"尝试更新的用户不存在\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "{\"error\": \"更新用户信息失败，请稍后重试\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/playlists/{playlistId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "歌单 (Playlist)"
                ],
                "summary": "获取歌单详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "歌单 ID",
                        "name": "playlistId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "歌曲列表页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "歌曲列表每页数量",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PlaylistDetailDTO"
                        }
                    }
                }
            }
        },
        "/songs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取公开的歌曲列表，支持分页、按歌曲名或艺术家名搜索、以及排序。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "歌曲 (Song)"
                ],
                "summary": "获取歌曲列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "搜索关键词 (匹配歌曲名或艺术家)",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "oldest",
                            "latest",
                            "play_count",
                            "like_count"
                        ],
                        "type": "string",
                        "description": "排序字段 (oldest, latest, play_count, like_count)",
                        "name": "sortBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.PaginatedResponseDTO"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "List": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.SongDetailDTO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"无效的查询参数\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "{\"error\": \"需要认证\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "{\"error\": \"获取歌曲列表失败\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/songs/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据歌曲ID获取单曲的详细信息，包括艺术家和专辑数据。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "歌曲 (Song)"
                ],
                "summary": "获取单曲详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "歌曲 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SongDetailDTO"
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"无效的歌曲ID格式\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "{\"error\": \"需要认证\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "{\"error\": \"歌曲未找到\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "{\"error\": \"获取歌曲详情失败，请稍后重试\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/songs/{id}/comments": {
            "get": {
                "description": "获取一首歌的根评论（非回复）的分页列表。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论 (Comment)"
                ],
                "summary": "获取歌曲评论",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "歌曲 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.PaginatedResponseDTO"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "List": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.CommentDTO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "为一首歌发表新评论，或回复一条已有的评论。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论 (Comment)"
                ],
                "summary": "发表评论",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "歌曲 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "评论内容",
                        "name": "createRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateCommentRequestDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.CommentDTO"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据用户ID获取用户的完整公开信息，包括关注数和粉丝数。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户信息 (User)"
                ],
                "summary": "获取用户个人资料",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserProfile"
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"无效的用户ID格式\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "{\"error\": \"需要认证\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "{\"error\": \"用户未找到\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "{\"error\": \"获取用户信息失败，请稍后重试\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/{id}/liked-songs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取指定用户的公开喜欢歌曲分页列表，支持搜索和排序。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "喜欢 (Like)"
                ],
                "summary": "获取指定用户的喜欢列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "搜索关键词 (匹配歌曲名或艺术家名)",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "latest",
                            "oldest",
                            "name",
                            "duration"
                        ],
                        "type": "string",
                        "description": "排序字段 (latest, oldest, name, duration)",
                        "name": "sortBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.PaginatedResponseDTO"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "List": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.SongDetailDTO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"无效的ID或查询参数\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "{\"error\": \"需要认证\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "{\"error\": \"获取喜欢的歌曲列表失败\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/{id}/name": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据用户ID获取用户的公开用户名和昵称。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户信息 (User)"
                ],
                "summary": "获取用户名和昵称",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UsernameResponse"
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"无效的用户ID格式\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "{\"error\": \"需要认证\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "{\"error\": \"用户未找到\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "{\"error\": \"获取用户名失败，请稍后重试\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/{id}/playlists": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "歌单 (Playlist)"
                ],
                "summary": "获取指定用户的歌单列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/models.PaginatedResponseDTO"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "List": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.PlaylistInfoDTO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AddSongToPlaylistRequestDTO": {
            "type": "object",
            "required": [
                "song_id"
            ],
            "properties": {
                "song_id": {
                    "type": "integer"
                }
            }
        },
        "models.Album": {
            "type": "object",
            "properties": {
                "cover": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "release_date": {
                    "type": "string"
                }
            }
        },
        "models.AlbumListDTO": {
            "type": "object",
            "properties": {
                "artist_names": {
                    "type": "string"
                },
                "cover": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "release_date": {
                    "type": "string"
                },
                "song_count": {
                    "type": "integer"
                }
            }
        },
        "models.Artist": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "sex": {
                    "type": "string"
                }
            }
        },
        "models.CommentDTO": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_liked_by_me": {
                    "type": "boolean"
                },
                "is_root": {
                    "description": "新增字段",
                    "type": "boolean"
                },
                "like_count": {
                    "type": "integer"
                },
                "parent_id": {
                    "description": "使用指针类型处理 NULL",
                    "type": "integer"
                },
                "replies": {
                    "description": "用于嵌套回复",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CommentDTO"
                    }
                },
                "reply_to_user_id": {
                    "description": "使用指针",
                    "type": "integer"
                },
                "reply_to_username": {
                    "type": "string"
                },
                "song_id": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.CreateCommentRequestDTO": {
            "type": "object",
            "required": [
                "text"
            ],
            "properties": {
                "parent_id": {
                    "type": "integer"
                },
                "reply_to_user_id": {
                    "type": "integer"
                },
                "text": {
                    "type": "string",
                    "maxLength": 1000
                }
            }
        },
        "models.CreatePlaylistRequestDTO": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "is_public": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.LikeCommentResponseDTO": {
            "type": "object",
            "properties": {
                "is_liked_by_me": {
                    "type": "boolean"
                },
                "like_count": {
                    "type": "integer"
                }
            }
        },
        "models.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.PaginatedResponseDTO": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "使用 interface{} 来适应任何类型的列表数据"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.PlaylistDetailDTO": {
            "type": "object",
            "properties": {
                "cover": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "creator_name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_public": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "song_count": {
                    "type": "integer"
                },
                "songs": {
                    "description": "复用分页结构",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.PaginatedResponseDTO"
                        }
                    ]
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.PlaylistInfoDTO": {
            "type": "object",
            "properties": {
                "cover": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "creator_name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_public": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "song_count": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.RegisterRequest": {
            "type": "object",
            "required": [
                "name",
                "password",
                "username"
            ],
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "birthday": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.SongDetailDTO": {
            "type": "object",
            "properties": {
                "album_cover": {
                    "type": "string"
                },
                "album_id": {
                    "type": "integer"
                },
                "album_name": {
                    "type": "string"
                },
                "artist_id": {
                    "type": "integer"
                },
                "artist_name": {
                    "description": "使用指针以防 JOIN 结果为 NULL",
                    "type": "string"
                },
                "author_id": {
                    "type": "integer"
                },
                "cover": {
                    "type": "string"
                },
                "create_time": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "is_public": {
                    "type": "boolean"
                },
                "like_count": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "play_count": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.UpdateCommentRequestDTO": {
            "type": "object",
            "required": [
                "text"
            ],
            "properties": {
                "text": {
                    "type": "string",
                    "maxLength": 1000
                }
            }
        },
        "models.UpdatePlaylistRequestDTO": {
            "type": "object",
            "properties": {
                "cover": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "is_public": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "birthday": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "gender": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "models.UserProfile": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "birthday": {
                    "type": "string"
                },
                "created_time": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "followers": {
                    "type": "integer"
                },
                "followings": {
                    "type": "integer"
                },
                "gender": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "description": "这里可能要返回比对, 而且反正是密文",
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "updated_time": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.UsernameResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "可以顺便带上昵称",
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Elaine 的音乐播放器 API",
	Description:      "这是一个使用 Go 语言和 Gin 框架开发的音乐播放器后端 API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
