/* tslint:disable */
/* eslint-disable */
/**
 * Elaine 的音乐播放器 API
 * 这是一个使用 Go 语言和 Gin 框架开发的音乐播放器后端 API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: your.email@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

